### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by tbugfinder** [marcuscaisey/.dotfiles#1]
Hi @marcuscaisey 
Thank you for your work on this python script.
Would it be possible to add a License like MIT/Apache 2.0 to this repo?

https://github.com/marcuscaisey/.dotfiles/blob/d9e9153acaa6ce26e4dcfd32b648d1f3c119c024/scripts/terraform-docs12#L1-L11

**Comment by marcuscaisey** [comment]
Yeah no worries
